import React from 'react';

type LegalView = 'privacy' | 'terms' | 'contact';

interface LegalPageProps {
  view: LegalView;
}

export const LegalPages: React.FC<LegalPageProps> = ({ view }) => {
  const containerClass = "max-w-4xl mx-auto py-12 px-6 prose prose-invert prose-p:text-gray-400 prose-headings:text-white prose-a:text-red-500";

  if (view === 'contact') {
    return (
      <div className="max-w-2xl mx-auto py-20 px-6">
        <h1 className="text-4xl font-display font-bold text-white mb-8 text-center">Contact Us</h1>
        <div className="bg-[#1a1a1a] p-8 rounded-xl border border-white/5">
          <p className="text-gray-400 mb-8 text-center">
            Have questions about ThumbGen AI? Need support with your API key? 
            We're here to help creators.
          </p>
          
          <form className="space-y-6" onSubmit={(e) => e.preventDefault()}>
            <div>
              <label className="block text-sm font-medium text-gray-300 mb-2">Email Address</label>
              <input type="email" className="w-full bg-[#0f0f0f] border border-white/10 rounded-lg p-3 text-white focus:ring-2 focus:ring-red-600 outline-none" placeholder="you@example.com" />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-300 mb-2">Subject</label>
              <select className="w-full bg-[#0f0f0f] border border-white/10 rounded-lg p-3 text-white focus:ring-2 focus:ring-red-600 outline-none">
                <option>General Inquiry</option>
                <option>Bug Report</option>
                <option>Feature Request</option>
                <option>Business / Advertising</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-300 mb-2">Message</label>
              <textarea className="w-full bg-[#0f0f0f] border border-white/10 rounded-lg p-3 text-white h-32 resize-none focus:ring-2 focus:ring-red-600 outline-none" placeholder="How can we help?"></textarea>
            </div>
            <button className="w-full bg-red-600 hover:bg-red-700 text-white font-bold py-4 rounded-lg transition-colors">
              Send Message
            </button>
          </form>

          <div className="mt-8 text-center border-t border-white/5 pt-8">
            <p className="text-xs text-gray-500">
              Or email us directly at: <a href="mailto:support@thumbgen.ai" className="text-white hover:text-red-500">support@thumbgen.ai</a>
            </p>
            <p className="text-xs text-gray-600 mt-2">
              Physical Address: 123 Creator Ave, Tech District, San Francisco, CA 94105
            </p>
          </div>
        </div>
      </div>
    );
  }

  if (view === 'terms') {
    return (
      <div className={containerClass}>
        <h1>Terms of Service</h1>
        <p>Last Updated: {new Date().toLocaleDateString()}</p>
        
        <h3>1. Acceptance of Terms</h3>
        <p>By accessing and using ThumbGen AI ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.</p>

        <h3>2. Description of Service</h3>
        <p>ThumbGen AI provides AI-powered image generation tools for YouTube thumbnails using Google's Gemini API. The Service is provided "as is" and "as available".</p>

        <h3>3. User Responsibilities</h3>
        <p>You agree to use the Service only for lawful purposes. You represent that you are responsible for maintaining the confidentiality of your API keys and for all activities that occur under your account usage.</p>

        <h3>4. Intellectual Property & Content Ownership</h3>
        <p>
          <strong>Generated Content:</strong> You retain full ownership rights to the images you generate using ThumbGen AI. You are free to use them for personal or commercial purposes (including monetized YouTube videos).
          <br/>
          <strong>Service Content:</strong> The design, code, and interface of ThumbGen AI are owned by us and protected by copyright laws.
        </p>

        <h3>5. API Usage</h3>
        <p>This application integrates with Google Gemini API. By using this tool, you also agree to be bound by Google's Generative AI Terms of Service. We do not store your API keys on our servers; they are used strictly within your browser session.</p>

        <h3>6. Disclaimer of Warranties</h3>
        <p>We do not guarantee that the Service will be uninterrupted, secure, or error-free. The AI-generated content may occasionally be inaccurate or offensive. We are not responsible for the content generated by the AI models.</p>

        <h3>7. Limitation of Liability</h3>
        <p>ThumbGen AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use the service.</p>
      </div>
    );
  }

  return (
    <div className={containerClass}>
      <h1>Privacy Policy</h1>
      <p>Last Updated: {new Date().toLocaleDateString()}</p>

      <p>At ThumbGen AI, accessible from https://thumbgen-ai.web.app, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by ThumbGen AI and how we use it.</p>

      <h3>Information We Collect</h3>
      <p>ThumbGen AI operates primarily as a client-side application. We do not store your personal data, generated images, or API keys on our servers.</p>
      <ul>
        <li><strong>API Keys:</strong> Your Google Gemini API key is stored locally in your browser (Local Storage) or memory for the duration of your session. It is never transmitted to our backend servers.</li>
        <li><strong>Uploaded Images:</strong> Images you upload for editing are processed locally within your browser.</li>
      </ul>

      <h3>Cookies and Web Beacons</h3>
      <p>Like any other website, ThumbGen AI uses "cookies". These cookies are used to store information including visitors' preferences, and the pages on the website that the visitor accessed or visited. The information is used to optimize the users' experience by customizing our web page content based on visitors' browser type and/or other information.</p>

      <h3>Google DoubleClick DART Cookie</h3>
      <p>Google is one of a third-party vendor on our site. It also uses cookies, known as DART cookies, to serve ads to our site visitors based upon their visit to www.website.com and other sites on the internet. However, visitors may choose to decline the use of DART cookies by visiting the Google ad and content network Privacy Policy at the following URL – <a href="https://policies.google.com/technologies/ads">https://policies.google.com/technologies/ads</a></p>

      <h3>Advertising Partners Privacy Policies</h3>
      <p>Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements and links that appear on ThumbGen AI, which are sent directly to users' browser. They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit.</p>
      <p>Note that ThumbGen AI has no access to or control over these cookies that are used by third-party advertisers.</p>

      <h3>Third Party Privacy Policies</h3>
      <p>ThumbGen AI's Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information.</p>

      <h3>CCPA Privacy Rights (Do Not Sell My Personal Information)</h3>
      <p>Under the CCPA, among other rights, California consumers have the right to request that a business that collects a consumer's personal data disclose the categories and specific pieces of personal data that a business has collected about consumers.</p>

      <h3>GDPR Data Protection Rights</h3>
      <p>We would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following: The right to access, rectification, erasure, restrict processing, object to processing, and data portability.</p>
    </div>
  );
};